### ISSUE TITLE
prismicide?

### ISSUE THREAD

**Issue by ulrichard** [LedgerHQ/ledger-blue#1]
Is the ledger-blue connected in any way to http://prismicide.com ?
Sounds very similar.

**Comment by btchip** [comment]
The goals of both projects were quite similar - the main difference is that Prismicide plans to build a fully Open Source solution, also regarding the Secure Element and radio parts, and is not funded - so progress is significantly slower and the end product will probably be significantly more expensive.

For the latest Prismicide status, you can check http://www.origamiboard.com/

**Comment by ulrichard** [comment]
Thanks for the info and the link.
So there is still hope I will actually receive something one day for my pledge to the prismicide crowdfunding.
